<?php $bearer = $this->request->get('bearer');?>
<header class="navbar navbar-dark sticky-t  echo $did ;op bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Cedcoss Technology</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" 
    type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3" href='http://localhost:8080/index/signout?bearer=<?php echo $bearer ?>'>Sign out</a>
      </div>
    </div>
  </header>
  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <?php echo $this->tag->linkTo([
                'product?bearer='.$bearer,
                 'Add Product',
                 "class" => "nav-link"
                  ]
                   );
                    ?>          
             </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                    'product/list?bearer='.$bearer,
                    'List all products',
                    'class' => 'nav-link'
                ]
                ); ?>  
            </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                'orders?bearer='.$bearer,
                'Place Order',
                'class' => 'nav-link'
            ]
            );?>  
            </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                    'orders/list?bearer='.$bearer,
                    'List all orders',
                    'class' => 'nav-link'
                ]
                ); ?>  
            </li>
            <li class="nav-item">
            <?php echo $this->tag->linkTo([
                'settings?bearer='.$bearer,
                'Update settings',
                'class' => 'nav-link'
            ]
            );?>  
            </li>
            <li class="nav-item">
              <?php echo $this->tag->linkTo([
                'user?bearer='.$bearer,
                 'Add User',
                 "class" => "nav-link"
                  ]
                   );
                    ?>          
             </li>
        
             <li class="nav-item">
              <?php echo $this->tag->linkTo([
                'user/list?bearer='.$bearer,
                 'List User',
                 "class" => "nav-link"
                  ]
                   );
                    ?>          
             </li>
             <li class="nav-item">
              <?php echo $this->tag->linkTo([
                'role/list?bearer='.$bearer,
                 'Add Role',
                 "class" => "nav-link"
                  ]
                   );
                    ?>          
             </li>
          </ul>
        </div> 
      </nav>
