<?php $role= $this->request->get('bearer'); ?>
<main class="form-signup my-5 text-center" style="padding-left:35%;padding-right:35%;">
 
 <?php echo $this->tag->form(""); ?>
 <h1 class="h3 mb-3 fw-normal">Place Order</h1>

  <div class="form-floating">
      <?php echo $this->tag->textField(["customerName","value"=>"","class"=>"form-control"]); ?>
      <label for="name">Customer Name</label>
     </div>

  <div class="form-floating">
       <?php echo $this->tag->textField(["address","value"=>"","class"=>"form-control"]); ?>
       <label for="address">address</label>
   </div>

  <div class="form-floating">
       <?php echo $this->tag->textField(["zip","value"=>"","class"=>"form-control"]); ?>
       <label for="zip">zip</label>
   </div>

   <div class="form-floating">
  
   <select name="product" class="w-100 p-2">
	<option value="">--- Choose a product ---</option>
    <?php for ($i=0; $i < count($data) ; $i++) { 
        ?> <option><?php echo $data[$i]->name;?></option><?php 
    } ?>
	
</select>

   </div>

   <div class="form-floating">  <?php

       echo $this->tag->textField(["quantity","value"=>"","class"=>"form-control"]); ?>
       <label for="quantity">quantity</label>
   </div>

  <div class="form-floating">
       <?php echo $this->tag->submitButton(
        ["name" => "placeOrder","value"=> "Place Order", "class" => "w-100 btn btn-lg btn-primary"]
); ?>
   </div>

   <div class="form-floating text-success">
       <?php if(isset($message))
       {
          echo $message;
       } ?>
   </div>

</form>