<?php include(APP_PATH.'/views/header/header.phtml'); ?>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
        </div>

        <h2>Orders</h2>
        <div class="table-responsive">
       <table class="table table-striped table-sm">
       <thead>
       <tr>
                    <th scope="col">Order id</th>
                    <th scope="col">Customer Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">Zip</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Action</th>

                 
                  </tr>
                </thead>
                <tbody>       
           <?php 
            foreach ($data as $k => $v){
              ?>
                  <tr>
                        <td> <?php echo $v->id  ?></td>
                        <td> <?php echo $v->customerName  ?></td>
                        <td> <?php echo $v->address  ?></td>
                        <td> <?php echo $v->zip  ?></td>
                        <td> <?php echo $v->product  ?></td>
                        <td> <?php echo $v->quantity  ?></td>
                       
                          <td><?php   echo $this->tag->linkTo(
                                  [
                                     "orders/update?id=$v->id",
                                     "Edit",
                                     "class" => "btn btn-primary"
                                  ]); 
                                  echo $this->tag->linkTo(
                                    [
                                       "orders/delete?id=$v->id",
                                       "Delete",
                                       "class" => "btn btn-danger"
                                    ]);
                                  
                                  ?></td></tr> <?php          
            }
            ?>  
          </tbody>
       </table>      
      </div>
         </form>


      </main>

