<?php include(APP_PATH.'/views/header/header.phtml'); 


?>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
        </div>

        <h2>Users</h2>
        <div class="table-responsive">
       <table class="table table-striped table-sm">
       <thead>
                  <tr>
                    <th scope="col"><?php echo $t->_('Id')?></th>
                    <th scope="col"><?php echo $t->_('Name')?></th>
                    <th scope="col"><?php echo $t->_('Description')?></th>
                    <th scope="col"><?php echo $t->_('Tags')?></th>
                    <th scope="col"><?php echo $t->_('Price')?></th>
                    <th scope="col"><?php echo $t->_('Stock')?></th>
                    <th scope="col"><?php echo $t->_('Action')?></th>
                  </tr>
                </thead>
                <tbody>
          
           <?php 
            foreach ($data as $k => $v){
              ?>
                  <tr>
                        <td> <?php echo $v->id  ?></td>
                        <td> <?php echo $v->name  ?></td>
                        <td> <?php echo $v->description  ?></td>
                        <td> <?php echo $v->tags  ?></td>
                        <td> <?php echo $v->price  ?></td>
                        <td> <?php echo $v->stock  ?></td>

                        <!-- Edit and delete options -->
                         <td> <?php  echo $this->tag->linkTo(
                                  [
                                     "product/update?id=$v->id",
                                     "Edit",
                                     "class" => "btn btn-primary"
                                  ]); 
                                  echo $this->tag->linkTo(
                                    [
                                       "product/delete?id=$v->id",
                                       "Delete",
                                       "class" => "btn btn-danger"
                                    ]);
                                  
                                  ?>

                                  </td></tr> <?php          
            }
            ?>  
          </tbody>
       </table>      
      </div>
         </form>


      </main>