<main class="form-signup my-5 text-center" style="padding-left:35%;padding-right:35%;">
 <?php echo $this->tag->form(""); ?>
 <h1 class="h3 mb-3 fw-normal">Hello User</h1>



  <div class="form-floating">
      <?php echo $this->tag->textField(["email","class"=>"form-control"]); ?>
      <label for="name">Email</label>
     </div>

     <div class="form-floating">
      <?php echo $this->tag->textField(["password","class"=>"form-control"]); ?>
      <label for="password">Enter Your Password</label>
     </div>

   
  <div class="form-floating">
       <?php echo $this->tag->submitButton(
       ["name" => "placeOrder","value"=> "Login", "class" => "w-100 btn btn-lg btn-primary"]
     ); ?>
   </div>
   <div class="form-floating text-danger">
       <?php if(isset($message))
       {
          echo $message;
       }
       ?>
   </div>
</form>