<?php include(APP_PATH.'/views/header/header.phtml'); ?>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
        </div>

        <h2>Users</h2>
        <div class="table-responsive">
       <table class="table table-striped table-sm">
       <thead>
       <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Role</th>
                    <td scope="col">ACTION</td>
                  </tr>
                </thead>
                <tbody>
          
           <?php 
            foreach ($data as $k => $v){
              ?>
                  <tr>
                        <td> <?php echo $v->id  ?></td>
                        <td> <?php echo $v->name  ?></td>
                        <td> <?php echo $v->email  ?></td>
                        <td> <?php echo $v->profile  ?></td>


                        <!-- Edit and delete options -->
                         <td> <?php  echo $this->tag->linkTo(
                                  [
                                     "user/update?id=$v->id",
                                     "Edit",
                                     "class" => "btn btn-primary"
                                  ]); 
                                  echo $this->tag->linkTo(
                                    [
                                       "user/delete?id=$v->id",
                                       "Delete",
                                       "class" => "btn btn-danger"
                                    ]);
                                  
                                  ?>

                                  </td></tr> <?php          
            }
            ?>  
          </tbody>
       </table>      
      </div>
         </form>


      </main>



